main: xyz.vedat.castleraid.CastleRaidMain
name: CastleRaid
version: 1.0.0
api-version: 1.16
api: "1.16"
authors: [ved]
commands:
    class:
        description: Pick a CastleRaid class.
        usage: "Usage: /<command> [alchemist|archer|assassin|berserker|builder|juggernaut|knight|mage|naturemage|sentry|sniper|spy|timewizard]"
    jointeam:
        description: Join a CastleRaid team.
        usage: "Usage: /<command> [RED|BLUE|WAITING|SPECTATOR]"
    newcrgame:
        description: Get new CastleRaid world.
        usage: "Usage: /<command>"
    forcestart:
        description: Force the lobby to start the game.
        usage: "Usage: /<command>"